#配置数据源
spring:
  datasource:
      url: jdbc:mysql://192.168.96.232:3306/viewhigh?useUnicode=true&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false&allowMultiQueries=true
      userName: "root"
      passWord: "7POHhYluSy"
      driver-class-name: com.mysql.jdbc.Driver
  output:
    ansi:
      enabled: always

# 配置MyBatis-Plus(具体各参数含义可参照 MyBatisPlusProperties.class 的各个属性))
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      db-type: mysql
      id-type: auto
      table-underline: true

# 配置log4g2
logging:
  level:
    com.pyi.config.mybatisplus: debug
  config:
    classpath: log4j2.yml

server:
  port: 8080
  servlet:
    context-path: /zxm

version: v1.0